name: Update Profile Banner

on:
  schedule:
    - cron: '0 0 * * *' # Har raat update hoga
  workflow_dispatch: # Manual run ka option bhi milega

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Banner Script
        run: |
          python generate_banner.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update terminal banner" || exit 0
          git push
